services:
  postgres:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pipeline_network
  spark:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SPARK_MODE=master
    ports:
      - "8080:8080"
    volumes:
      - ./data/input:/data/input
      - ./data/checkpoints:/data/checkpoints
      - ./scripts:/scripts
      - ./config:/config
      - ./sql:/sql
    depends_on:
      - postgres
    networks:
      - pipeline_network
networks:
  pipeline_network:
    driver: bridge
volumes:
  postgres_data:
