apiVersion: 1

datasources:
  - name: HeartbeatDB
    type: postgres
    url: postgres:5432
    database: ${POSTGRES_DB}
    user: ${POSTGRES_USER}
    jsonData:
      sslmode: disable
      postgresVersion: 1600
    secureJsonData:
      password: ${POSTGRES_PASSWORD}
